@base_url = http://localhost:5000/api

// ======== GET ALL POSTS ======== (token required)
GET {{base_url}}/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmQ1NzQ0NTQ5ZTJmODJjNWFmODMzMCIsImlhdCI6MTY1MTQwMDEyOCwiZXhwIjoxNjUzOTkyMTI4fQ.XC6Yx6rU7HPhCyOWWbEaCIdWKkM4ndmn_aZPm_RF-go
###

// ======== CREATE POST ======== (token required)
POST {{base_url}}/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmQ0ZjY0NTQ5ZTJmODJjNWFmODMxZCIsImlhdCI6MTY1MTQwMTAyOSwiZXhwIjoxNjUzOTkzMDI5fQ.fWt3P671ahc8TJ31k8whs_j4O2Vplw09OA_AQvVs1c0
Content-Type: application/json

{
    "text": "freddes new post"
}
###

// ======== UPDATE POST ======== (id at the end of url required) (token required)
PUT {{base_url}}/posts/62692e9e2fe2905a936fb4a4
Authorization: Bearer <TOKEN>
Content-Type: application/json

{
    "text": "test text"
}
###

// ======== DELETE POST ======== (id at the end of url required) (token required)
DELETE {{base_url}}/posts/626e5d8de36301fe401eb7f5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmQ0ZjY0NTQ5ZTJmODJjNWFmODMxZCIsImlhdCI6MTY1MTQwMTEzMCwiZXhwIjoxNjUzOTkzMTMwfQ.lcpx3vgUUYLPMJWoBsw7N-VQV4-5cbkRM8BYx5Hx37g
###