@base_url = http://localhost:5000/api

// ======== SIGNUP ========

POST {{base_url}}/users
content-type: application/json

{
    "name": "holger",
    "email": "holger@holger.com",
    "password": "qwerty123"
}
###

// ======== LOGIN ========
POST {{base_url}}/users/login
content-type: application/json

{
    "name": "fredde",
    "email": "fredde@fredde.com",
    "password": "qwerty123"
}
###

// ======== GET USER by token ======== (token required)
GET {{base_url}}/users/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmQ0ZjY0NTQ5ZTJmODJjNWFmODMxZCIsImlhdCI6MTY1MTM5OTU1OCwiZXhwIjoxNjUzOTkxNTU4fQ.JM0sR8YOUaHBN4LvutwdL33LvD691blkFDnQ6TylTyI